// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

namespace WebApi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200918192125_ContextUpdate")]
    partial class ContextUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Models.Variables", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressIn");

                    b.Property<int>("AddressOut");

                    b.Property<string>("Avalue");

                    b.Property<string>("Bit_position");

                    b.Property<string>("Buttonpath");

                    b.Property<string>("Bvalue");

                    b.Property<string>("Code");

                    b.Property<bool>("Decimal");

                    b.Property<int>("Defaultvalue");

                    b.Property<int>("Delay");

                    b.Property<int>("Delta");

                    b.Property<string>("Description");

                    b.Property<string>("DetailId");

                    b.Property<string>("DeviceModel");

                    b.Property<int>("Dimension");

                    b.Property<int>("Frequency");

                    b.Property<string>("Functioncode");

                    b.Property<int>("Grpcategory");

                    b.Property<int>("Idgroup");

                    b.Property<int>("Idhsvariable");

                    b.Property<string>("Idvariable");

                    b.Property<string>("Idvarmdl");

                    b.Property<string>("Imageoff");

                    b.Property<string>("Imageon");

                    b.Property<string>("Inserttime");

                    b.Property<bool>("Isactive");

                    b.Property<bool>("Iscancelled");

                    b.Property<bool>("Ishaccp");

                    b.Property<bool>("Islogic");

                    b.Property<bool>("Isonchange");

                    b.Property<string>("Lastupdate");

                    b.Property<int>("Length");

                    b.Property<string>("Maximum");

                    b.Property<string>("Measureunit");

                    b.Property<string>("Minimum");

                    b.Property<int>("Priority");

                    b.Property<int>("ReadWrite");

                    b.Property<int>("Rowid");

                    b.Property<bool>("Signed");

                    b.Property<string>("ToDisplay");

                    b.Property<int>("Type");

                    b.Property<string>("VId");

                    b.Property<string>("Varencoding");

                    b.HasKey("Id");

                    b.ToTable("variables");
                });
#pragma warning restore 612, 618
        }
    }
}
